name: Auto Commit Farm

on:
  schedule:
    - cron: '0 * * * *' # Runs at minute 0 of every hour
  workflow_dispatch:

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make a dummy change
        run: |
          echo "Harvested a green square on $(date)" >> .commit_log

      - name: Commit and Push
        run: |
          git config --global user.name "ZRayce"
          git config --global user.email "zerorayce@gmail.com"
          
          git add .commit_log
          git commit -m "chore: farm another green square"
          git push
